CREATE TABLE DB_LOGGER_LOG_CONFIG (
  ID_LOG_CONFIG NUMBER				  NOT NULL,
  CONFIG_KEY	  VARCHAR2(64) 		NOT NULL,
  CONFIG_VALUE	VARCHAR2(128) 	NOT NULL,
  CONSTRAINT 	PK_TB_LOG_CONFIG 	PRIMARY KEY(ID_LOG_CONFIG)
);